### ISSUE TITLE
People are unable to log in

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#283]
It seems that some people are not receiving emails with keys in them (for accounts without passwords). No signs of a problem on our end yet. Need to come up with a couple theories to start debugging. Will anonymize and post user problems.

- [ ] any emails stuck in outbound queue?
- [ ] http post to SQS failing?
- [ ] any logs with errors in them *anywhere*?
- [ ] are people using the wrong emails and we just aren't telling them?

**Comment by secretrobotron** [comment]
> When I click sign-up, I'm told my email has already been registered. When I used the "key" I was sent, I get a message saying that key is incorrect.

**Comment by secretrobotron** [comment]
> My students and I are unable to access our Popcorn Maker accounts at 2:00 on Monday, April, 20, 2015. The webpage is working as normal, but none of us are receiving our sign-in keys via email. I have tried to sign in about five times or more in the last hour.
These are not new accounts, and we had no problems accessing our accounts as recently as last Friday.

**Comment by secretrobotron** [comment]
> I’ve been working on a project using the popcorn movie marker, my username is ********, and today when I went to sign in I never received the email with the confirmation code. I’ve tried to have the email sent at least 5 times by trying to login multiple times, and I’ve checked my spam folder for the past 30 minutes but still I haven’t received anything.

**Comment by secretrobotron** [comment]
> My daughter created a webpage using this site and used the username - ******** and thought she used the email ***********.  Unfortunately no matter how many times we try, we can not get a confirmation or a key link sent to her email.  She doesn't remember setting a password and in the class they didn't provide anything to write the information down.  Is there anyway you can help us get her access into her page that should be associated with this username and a similar (but probably mistyped email address)?

**Comment by secretrobotron** [comment]
Things we should do:
- measuring time from user request to email sent
- see if users are on SES block list
- get notified when redis fails, and try to recover
- check the handful of users we know are having problems to see if we can tell which keys they tried to use, and see if they match the last key the were emailed

**Comment by jbuck** [comment]
Additional options: look at using exact target as a back-up or the primary method of sending email.

**Comment by simonwex** [comment]
We also need a plan for surfacing to the user that emails to their address failed during sign-up.

@jbuck there's Exact Target training going on next week, do you want in?

**Comment by jbuck** [comment]
To remove people from the suppression list we need to do the following: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/remove-from-suppression-list.html

**Comment by secretrobotron** [comment]
@adamlofting: would love to track # of people that are failing to log in or sign up. @jbuck put together a query for the logins token database that showed us the % of people that didn't use the login token we'd given them. Would love that to be on a dashboard somewhere, and/or gather more insight from GA where possible. Can you help?

**Comment by secretrobotron** [comment]
@jbuck is filing bugs based on https://github.com/mozilla/id.webmaker.org/issues/283#issuecomment-96836570 and our phone chat. Will come up with some instrumentation to check this.

**Comment by adamlofting** [comment]
Happy to help but to manage expectations I'm unlikely to get time this week, and I'm on PTO next week. 

What are the data points we want to put on a dashboard? (as there are a few ways to fail to login). Let's query the data manually for now to debug. Once we know what data indicates the problem at hand we can build a dashboard and/or monitoring solution to keep an eye on that problem.

**Comment by secretrobotron** [comment]
We were actually hoping to do the opposite, since we have no idea if/how login failures happen. It would be useful to have the query @jbuck ran manually ("how many users have unused login keys more than an hour old", I think) run through a cron job (or something) and to splash that number on an existing dashboard (http://metrics.webmaker.org/? <-- looks to be down atm, btw).

**Comment by adamlofting** [comment]
I'm not yet convinced that graphing the % of people who don't login is going to help us debug this problem. And the time to setup the automation is what makes adding something to the dashboard a slowish process (I'd estimate ~4hrs work which I don't have this week).

But I've graphed the recent historic data so you can see what a daily graph would look like:

![tokens used](https://cloud.githubusercontent.com/assets/1901816/7411181/6feab484-ef2d-11e4-8d0a-7070494b8d16.jpg)

![tokens used](https://cloud.githubusercontent.com/assets/1901816/7411185/756f2822-ef2d-11e4-8c6c-0cc74a370b65.jpg)

About 65% of tokens get used, and something weird happened on 20th April.

**Comment by adamlofting** [comment]
It might be worth running some queries to join this token data with other user data to see if the unused tokens are biased in some way (e.g. are they all new accounts that never activate, or are they all hotmail email addresses, and so on.)

**Comment by amirad** [comment]
I've been emailing all the individuals who have had issues. I'm still getting a couple new emails every day. 

Here's a couple of the responses I got
"After waiting for about 2 hours I received all of the emails at once and now receive them instantly."
"The system seems to have resolved itself later that day. I received about 8 sign-in keys in a row at five or six in the evening (five  hours after making several attempts to access my account)."

**Comment by simonwex** [comment]
@jbuck could you do some digging to see where this delay/queuing is occurring?

**Comment by jbuck** [comment]
Implementation idea for recording SES suppression list bounces:

##### Part 1 (Metrics & bounce prevention)
- [ ] Configure current bounce topic to deliver bounce notifications to current sawmill SQS queue
- [ ] Configure DynamoDB table that's able to be written to by sawmill
- [ ] Write a worker in sawmill that processes bounce notifications by taking the email address that bounced and putting it in a DynamoDB table
- [ ] Modify the current email sending workers in sawmill to look-up the email address in our bounce list before sending

##### Part 2 (User-facing bounce prevention)
- [ ] Modify id.wm.o and/or login.wm.o to look-up the email address in our bounce list before sending out request
- [ ] Modify id.wm.o and/or login.wm.o to look-up the email address domain via DNS to see if it's a valid domain (look for MX record, specifically)

**Comment by jbuck** [comment]
@simonwex sawmill production was down for 5 hours on the 26th due to redis timeouts, and poor error handling on our part:

```
2015-04-26T03:14:04Z	Error: Redis connection to ray.redistogo.com:9847 failed - read ETIMEDOUT
2015-04-26T03:14:05Z	State changed from up to crashed
2015-04-26T03:14:05Z	State changed from crashed to starting
2015-04-26T03:14:08Z	State changed from starting to up
2015-04-26T03:14:10Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T03:14:11Z	State changed from up to crashed
2015-04-26T05:26:51Z	State changed from crashed to starting
2015-04-26T05:26:53Z	State changed from starting to up
2015-04-26T05:26:55Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T05:26:55Z	State changed from up to crashed
2015-04-26T05:38:53Z	State changed from crashed to starting
2015-04-26T05:38:55Z	State changed from starting to up
2015-04-26T05:38:57Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T05:38:57Z	State changed from up to crashed
2015-04-26T06:12:07Z	State changed from crashed to starting
2015-04-26T06:12:11Z	State changed from starting to up
2015-04-26T06:12:13Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T06:12:14Z	State changed from up to crashed
2015-04-26T07:15:21Z	State changed from crashed to starting
2015-04-26T07:15:25Z	State changed from starting to up
2015-04-26T07:15:28Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T07:15:29Z	State changed from up to crashed
2015-04-26T07:34:59Z	State changed from crashed to starting
2015-04-26T07:35:04Z	State changed from starting to up
2015-04-26T07:35:05Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T07:35:09Z	State changed from up to crashed
2015-04-26T07:47:06Z	State changed from crashed to starting
2015-04-26T07:47:09Z	State changed from starting to up
2015-04-26T07:47:10Z	Error: Redis connection to ray.redistogo.com:9847 failed - connect ECONNREFUSED
2015-04-26T07:47:11Z	State changed from up to crashed
2015-04-26T08:39:50Z	State changed from crashed to starting
2015-04-26T08:39:53Z	State changed from starting to up
```

https://github.com/mozilla/sawmill/blob/fb25eb212f08c2d9aaa6565f31ea4a14b200a504/processor.js#L66-L68 is the offending line of code that needs to be fixed

**Comment by simonwex** [comment]
@jbuck do we have an alert that will now fire if a similar error occurs?

**Comment by jbuck** [comment]
@simonwex I setup an alert in papertrailer for the text "crashed" so that should catch it

**Comment by jbuck** [comment]
Since the last update here we've switched to Heroku Redis which has been more reliable and we've been recording the bounces in sqs. I believe the eventual plan would be to switch to a more reliable/fully-featured transactional email provider. For now, not doing any more work here.
