### ISSUE TITLE
Pages meta ticket

### ISSUE THREAD

**Issue by alicoding** [mozilla/id.webmaker.org#76]
TODO:

**LOGIN**
Design ticket #27 
Implementation ticket #6 
- [x] Checkmark when validated
- [ ] postfix (username.makes.org)
- [x] add "Need help?" link to the box

**Reset password**
Design ticket #30 
Implementation ticket #7 
- [x] make the banner for step 2 to match the design
- [x] create readonly field for username
- [x] add checkmark
- [x] change the label to "Set a new password"

**User migration**
Design ticket #28 
Implementation ticket #53 
- [x] DO EVERYTHING!

**Signup**
Design ticket #29 
Implementation ticket #8 
- [x] add warning label for error cases
- [ ] add postfix (username.makes.org)

cc @Pomax

**Comment by alicoding** [comment]
The only thing that I have to skip since I can't come up with a good quick solution right now is the postfix text in the input username field. I'm going to finish up the user migration page hopefully tomorrow before the demo.

It is pretty much ready for QA, but we need to hook up with the API and setup any logic we want. We do have everything in place for client side but just need to make it do something real.

cc @secretrobotron, @cassiemc and @Pomax

**Comment by alicoding** [comment]
The only thing I did not do in the UI implementations is the postfix which I need to think for a good solution to do this...
![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/u56fqvhx.png)

**Comment by secretrobotron** [comment]
@alicoding is there a bug specifically for postfix? OK to skip this heartbeat if it's filed for later.

**Comment by alicoding** [comment]
I will file them now
