### ISSUE TITLE
Metrics: Requirements for Analytics and Database

### ISSUE THREAD

**Issue by adamlofting** [mozilla/id.webmaker.org#77]
I'm closing the requirements gathering checklist https://github.com/mozilla/id.webmaker.org/issues/56 as we need to move on implementation. 

## Known tasks:

For @adamlofting and or dev support (TBC @simonwex)

- [x] Setup a new GA property via MoCo for id.webmaker.org ([Bug is here](https://bugzilla.mozilla.org/show_bug.cgi?id=1149508))
- [x] Setup basic Google Analytics in the id.webmaker.org codebase ([PR is open here #93](https://github.com/mozilla/id.webmaker.org/pull/93))
  * Use [react-ga](https://github.com/adamlofting/react-ga) module to do this
- [x] Review the front-end experience and tech stack to see what tracking beyond basic pageviews is required
- [x] Setup GA tracking of the in-page event tracking we care about (validation errors, field focus, etc) #137 
- Setup conversions Goals and funnels in the GA account
  - [x] Account creation and login
  - [ ] Field by field funnel
- [x] Ensure we're tracking pageload times as part of our GA configuration
- [x] Solve / Spec how we identify traffic sources (teach / webmaker / other) within the GA reporting (this is covered by standard GA referral data) 
- [ ] Solve / Spec how we update GA code, and reporting configuration across all other properties currently using login
- [x] Not a blocker: Proof of concept implementation for Optimizely

## Open Questions:

For @jbuck, @secretrobotron, or others in the know.

- [x] Are we replacing the existing `Users` table that sits behind the current login platform?
  * This shouldn't block or slow down shipping, but will cause a bunch of knock-on work for our integration db and KPI dashboards
- [x] Are we launching just with teach, or swapping out all instances of login at the same time?
- [x] Did we preserve the existing work on the [Referrer API](https://wiki.mozilla.org/Webmaker/Maker_Party/referrer_api) and [this](https://github.com/mozilla/login.webmaker.org/commit/b87b38ce308d84e347d1742584a0c7bd57413953), or has this been killed? Solved in #97
- [x] How will we identify in the database, the difference between Webmaker Account Holders, and Webmaker Users? We need some kind of table or flag to say which sites the user has authenticated against. Example query I'd want to be able to run = `show me all account holders who use teach.m.o but never webmaker.org`. Solved in #97

## Reporting Requirements: 

For @adamlofting

### For ID as a standalone Service

Conversion rates
- [x] UV to Sign Up 
- [x] UV to Log In 
*GA Goals Setup*

Abandon rate
- [x] % of users who start but never complete sign up
- [x] % of users who start but never complete log in
- [x] overall bounce rate - users who land on id.w.o but don't start sign up or log in
*These can be seen in standard GA reporting using the Goals*

Abandon funnel
- [ ] % of users who exit the funnel at each stage of sign up (by view is fine, but by input is better)
- [ ] % of users who exit the funnel at each stage of log in (by view is fine, but by input is better)

Error frequency
- [x] Break down of validation errors by message and both % and # of occurrences (this being recorded in GA)
- [ ] Break down of HTTP errors (404s, 500s, etc) created by both the API and WWW interface (TBC where we want to measure this)

### For Products that use the ID Service (webmaker and teach.m.o)
- [ ] Need to see users who go out to id.w.o, and then return as part of a single session
- [ ] Before and after reporting of impact on existing tools and users
- [ ] Before and after reporting of email opt-in rate given the new UX (separating the two checkboxes)

**Comment by adamlofting** [comment]
##### Pings:
@jbuck @secretrobotron could you have a look at these open questions please?
@simonwex is there dev capacity here, or is it best I start hacking on this myself?
@thisandagain cc/ re: requirement to identify accounts by the sites they have used

**Comment by simonwex** [comment]
@secretrobotron, could we add this to the stack to consider tomorrow during our login triage?

**Comment by secretrobotron** [comment]
@simonwex  :+1: Can remain in this milestone to review.

@adamlofting trying to answer q's. @jbuck can confirm:

> Are we replacing the existing Users table

@jbuck's proposal was to keep the old table around, while using a new table to store new/updated users. So, both will be in use until a certain (yet unspecified) date.

> Are we launching just with teach, or swapping out all instances of login at the same time?
Just focusing on teach for now.

> Did we preserve the existing work on the Referrer API

My guess is no, but @cadecairos and @jbuck should confirm. I know we'll still have a referral system, but the API might not match.

> How will we identify in the database

If that's not implemented in the storage layer right now, we can add it in. For now, all users are teach users, so we should be able to add in a system to distinguish accounts from users later on without blocking this heartbeat.

**Comment by adamlofting** [comment]
I've just opened PR #93 to add basic pageview tracking using [react-ga](https://github.com/adamlofting/react-ga)

I started walking through the UX. Notes to self: `/login` `/signup` `/migrate` `/reset-password`

But I can't create accounts etc yet locally to see all the places that will need instrumentation. I'm catching up with @secretrobotron later today, and will update this ticket further after that.

**Comment by adamlofting** [comment]
GA property is now setup: `UA-49796218-21`

**Comment by adamlofting** [comment]
Optimizely has landed and can be switched on/off with an environment variable so we're only loading the extra script while we're testing.

**Comment by adamlofting** [comment]
I've just updated the status of each of the checkbox items on this ticket.

We're getting close to being done, and if we keep the momentum I think this will all be ready for Friday.

**Comment by secretrobotron** [comment]
Most of this is done, and what isn't doesn't need to block. @adamlofting will move what's left into tickets and close this by tomorrow.

**Comment by adamlofting** [comment]
id.w.o will launch with better instrumentation than our existing webmaker properties. There are a few remaining tasks that won't make sense until we roll-out id to existing webmaker tools and services, and I've moved these to a backlog ticket so that we can close this.

Especially big thanks to @alicoding for implementing the GA tracking, and @jbuck for the oAuth client logging table :dizzy: :boom: :star2: :boom: :dizzy:
