### ISSUE TITLE
Metrics QA / pre-flight checklist

### ISSUE THREAD

**Issue by adamlofting** [mozilla/id.webmaker.org#78]
- [x] All the requirements from the kickoff checklist https://github.com/mozilla/id.webmaker.org/issues/77 have been implemented
- [x] Basic Goggle Analytics (GA) pageview tracking is present
- [x] GA is using the correct account ID for the domain where this project is hosted
- [x] GA pageview and event data is showing up in the realtime reports when tested in staging environment
- [x] If conversion goals are being tracked, these have been configured in GA
- [x] If required, custom GA events tracking is present
- [x] If required, Optimizely standard tag is present
- [x] If required, Optimizely conversion goals have been instrumented
- [x] If required, reporting is ready

**Comment by secretrobotron** [comment]
:+1: :mushroom: :necktie:
